name: Check CHANGELOG.md has been written.

on:
  workflow_call:
    secrets:
      tinkoff_bot_pat:
        required: true

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Check if github-token is set
        run: |
          if [ -z "${{ secrets.tinkoff_bot_pat }}" ]
          then
            echo "Error: TINKOFF_BOT_PAT is not set." >&2
            exit 1
          fi

      - uses: actions/checkout@v3

      - name: Get changed files
        uses: actions/github-script@v4
        id: files
        with:
          github-token: ${{ secrets.tinkoff_bot_pat }}
          script: |
            const { data: files } = await github.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const firstFilePath = files[0].filename
            const hasChangelog = files.some(file => file.filename === 'CHANGELOG.md');
            if (!hasChangelog) {
              console.log('CHANGELOG.md not found in pull request files');
              console.log('Please update the CHANGELOG.md file.');
              const comment = `
              🤠 Please update the **CHANGELOG.md** file.
              > Keep on going sir, next time do not break the rules 🫡
              `;
              core.setOutput('comment', comment);
              core.setOutput('filePath', firstFilePath);
            }

      - name: Add comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.tinkoff_bot_pat }}
          script: |
            async function createReviewComment() {
              const comments = [
                {
                  path: `${{ steps.files.outputs.filePath }}`,
                  body: `${{ steps.files.outputs.comment }}`,
                  position: 0
                }
              ]
              
              await github.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                comments: comments   
            });
            }

            await createReviewComment();